# You can use this file to setup the service locally, and start all the
# containers at once.
#
# Usage:
# - setup all the environment variables referenced below
# - install Docker Compose, see https://docs.docker.com/compose/install
# - open a console and `cd` into the folder that contains this file
# - run `docker-compose up`

version: "3"

services:
  devicesimulation:
    image: azureiotpcs/device-telemetry-java
    ports:
      - "9004:9004"
    environment:
      - PCS_DEVICE_TELEMETRY_WEBSERVICE_PORT=9004
